theme = "ashen"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "version-control", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = false
git-ignore = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection" ]

[keys.normal.space]
l = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit",
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]

[keys.normal."+"]
d = [":sh rm %{buffer_name}", ":buffer-close" ] # Remove current file
