theme = "rose_pine_moon"

[editor]
line-number = "relative"
cursorline = true
mouse = false

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "version-control", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = false
git-ignore = false
git-exclude = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection" ]

[keys.normal.space]
l = [
    ":write-all", 
    ":new", 
    ":run-shell-command tmux new-window -n lazygit -c \"$(pwd)\" \"cd $(git rev-parse --show-toplevel 2>/dev/null || pwd) && lazygit; tmux kill-window\"",
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]

[keys.normal."+"]
d = [":sh rm %{buffer_name}", ":buffer-close" ] # Remove current file
