theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["version-control", "mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
