theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["version-control", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", ":reload-all"]

[keys.normal.space]
l = [
    ":write-all", 
    ":new", 
    ":run-shell-command tmux new-window -n lazygit -c \"$(pwd)\" \"cd $(git rev-parse --show-toplevel 2>/dev/null || pwd) && lazygit; tmux kill-window\"",
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
] # Open lazygit
B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}" # Git blame

[keys.normal."+"]
d = [":sh rm %{buffer_name}", ":buffer-close" ] # Remove current file
