[[language]]
name = "ruby"
auto-format = false
language-servers = ["solargraph"]

[language-server.solargraph]
command = "/home/hdu/.rbenv/versions/3.3.0/bin/solargraph"
args = ["stdio"]

[[language]]
name = "lua"
roots = [".luarc.json"]
