gui:
  skipDiscardChangeWarning: false
  language: 'en'
  theme:
    cherryPickedCommitBgColor:
      - "#282828"
    cherryPickedCommitFgColor:
      - "#4EC9B0"
    defaultFgColor:
      - "#d4d4d4"
    inactiveBorderColor:
    optionsTextColor:
      - "#dcdcaa"
    searchingActiveBorderColor:
      - "#4EC9B0"
      - "bold"
    selectedLineBgColor:
      - "#282828"
    unstagedChangesColor:
      - "#f44747"
    activeBorderColor:
      - "#4085C9"
      - "bold"

os:
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{filename}} && nvim --server "$NVIM" --remote-send "{{line}}gg")'
  openDirInEditor: '[ -z "$NVIM" ] && (nvim -- {{dir}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{dir}})'
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{filename}})'
  openInTerminal: '[ -z "$NVIM" ]'
  editPreset: 'nvim-remote'
