#!/usr/bin/env bash

WALLPAPER_DIR="$HOME/Pictures/Wallpapers"

image_files=$(find "$WALLPAPER_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' -o -iname '*.webp' \))
symlinks=$(find "$WALLPAPER_DIR" -type l)

wallpapers=$(echo -e "$image_files\n$symlinks" | sort)

chosen=$(echo "$wallpapers" | rofi -dmenu -i -p "Set wallpaper:")

if [ -n "$chosen" ]; then
    feh --bg-scale "$chosen"
    notify-send " Wallpaper set" "$(basename "$chosen")"
fi
