#!/usr/bin/env bash

# Get current sessions
selected=$(tmux list-sessions -F "#{session_name}" | fzf --info=hidden --no-color)

# If nothing is chosen - quit
[[ -z $selected ]] && exit 0

# If inside tmux - switch client
if [[ -n $TMUX ]]; then
    tmux switch-client -t "$selected"
else
    tmux attach-session -t "$selected"
fi
