#!/usr/bin/env bash

# Get current sessions
selected=$(tmux list-sessions -F "#{session_name}" | \
	fzf --height=50% --info=hidden --margin=10% --no-color)

# If nothing is chosen - quit
if [[ -z $selected ]]; then
    exit 0
fi

# If inside tmux - switch client
if [[ -n $TMUX ]]; then
    tmux switch-client -t "$selected"
else
    tmux attach-session -t "$selected"
fi
