#!/usr/bin/env bash

# Pick directory
selected=$(find ~ -type d -mindepth 1 \
  -not -path '*/.git/*' \
  2>/dev/null | sed "s|^$HOME/||" | \
  fzf --height=50% --info=hidden --margin=10% --no-color)

# If nothing is chosen - quit
if [[ -z $selected ]]; then
    exit 0
fi

dir="$HOME/$selected"
session=$(basename "$selected")

# Create session if it doesn't exist
if ! tmux has-session -t "$session" 2>/dev/null; then
    tmux new-session -ds "$session" -c "$dir"
fi

# Switch or attach
if [[ -n $TMUX ]]; then
    tmux switch-client -t "$session"
else
    tmux attach-session -t "$session"
fi
