# My aliases
alias c='clear'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias zrc='vim ~/.zshrc'
alias sz='source ~/.zshrc'
alias act='source venv/bin/activate'
alias deact='deactivate'
alias py='python'
alias v='sudo vim'
alias ins='sudo pacman -S'
alias binds='v .config/sxhkd/sxhkdrc'
alias locate='sudo find / -name'
alias smci='sudo make clean install'
alias smcu='sudo make clean uninstall'
alias smi='sudo make install'
alias smu='sudo make uninstall'
