set -g default-terminal "tmux-256color"  # Better than screen-256color
set -ag terminal-overrides ",xterm-256color:RGB"  # Force true color

set -sg escape-time 0
set-option -g focus-events on

set -g status-interval 0 # never update status line

set -g base-index 1 # start window numbering at 1
setw -g pane-base-index 1 # start pane numbering at 1
set-option -g renumber-windows on # auto-renumber windows when one is closed

##### Mouse and Clipboard Integration #####
set -g mouse on
set -g focus-events on

# Use system clipboard with xclip
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind -T copy-mode-vi Space send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

##### Keymaps ####
bind r source-file ~/.tmux.conf \; display "Sourced config!"
bind f display-popup -B -E "~/.tmux/tmux-sessionizer"
bind -n F3 switch-client -l
bind -n F4 last-window
bind v capture-pane -S - \; \
  save-buffer /tmp/tmux \; \
  delete-buffer \; \
  new-window -n "vim-tmux-capture" -c "#{pane_current_path}" \
    "vim /tmp/tmux && rm -f /tmp/tmux; tmux kill-window"

# Vim-style copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Open windows without prefix (with alt)
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Other keymaps without prefix (with alt)
bind -n M-f display-popup -B -E "~/.tmux/tmux-sessionizer"
bind -n M-z resize-pane -Z

# Vim-like moving (with alt)
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

##### Status Line #####
set -g status-position top # position the status line at the top
set -g status-style bg=default # style of the status line
set -g status-left "#[fg=#888888,bold]#S " # left side content: session name
set -g status-right "" # right side content is empty

# Format window titles
set -g window-status-separator " "
setw -g window-status-format "#[fg=#888888]#I:#W"
setw -g window-status-current-format "#[fg=#DDDDDD]#I:#W"
