theme = "dark_plus"

[editor]
line-number = "relative"
cursorline = true

[editor.statusline]
left = ["version-control", "mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
